"""
PetCircle Phase 1 — Document Model

Mirrors the 'documents' table exactly as defined in the frozen SQL schema.

Constraints:
    - pet_id: FK to pets(id), ON DELETE CASCADE
    - extraction_status: CHECK IN ('pending', 'success', 'failed')
    - file_path: storage path ({user_id}/{pet_id}/{filename}), same path for both backends
    - mime_type: validated against ALLOWED_MIME_TYPES at service layer
    - storage_backend: 'gcp' (primary) or 'supabase' (fallback/legacy)
"""

import uuid
from datetime import datetime

from sqlalchemy import Column, Date, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.database import Base


class Document(Base):
    """
    Represents an uploaded document (image or PDF) for a pet.

    Documents are stored in the private Supabase bucket at the path
    {user_id}/{pet_id}/{filename}. No public URLs are ever generated.

    After upload, GPT extraction processes the document to extract
    structured preventive health data. The extraction_status tracks
    this pipeline: pending → success/failed.
    """

    __tablename__ = "documents"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Foreign key to pets table.
    # ON DELETE CASCADE — removing a pet removes its documents.
    pet_id = Column(UUID(as_uuid=True), ForeignKey("pets.id", ondelete="CASCADE"), index=True)

    # Storage path in Supabase bucket: {user_id}/{pet_id}/{filename}.
    # Never contains public URLs — access is always through signed URLs.
    file_path = Column(String, nullable=False)

    # MIME type of the uploaded file.
    # Validated against ALLOWED_MIME_TYPES (image/jpeg, image/png, application/pdf)
    # at the service layer before insertion.
    mime_type = Column(String(50), nullable=False)

    # Human-readable document name classified by GPT during extraction.
    # Examples: "Blood Test Report", "Vaccination Certificate", "Deworming Record".
    # Set to None initially, populated after extraction completes.
    document_name = Column(String(200), nullable=True)

    # Document category assigned by GPT extraction.
    # Values: "Vaccination", "Prescription", "Diagnostic", "Other".
    # Used for grouping documents in the dashboard display.
    document_category = Column(String(30), nullable=True)

    # Vet/doctor name extracted from medical documents when available.
    doctor_name = Column(String(200), nullable=True)

    # Hospital/clinic name extracted from medical documents when available.
    hospital_name = Column(String(200), nullable=True)

    # GPT extraction pipeline status:
    # 'pending'             — uploaded, awaiting extraction
    # 'success'             — extraction completed, structured data saved
    # 'partially_extracted' — metadata extracted but zero preventive items found
    # 'failed'              — extraction failed after retries
    # 'rejected'            — document is not pet-related or is for a different pet
    extraction_status = Column(String(20), nullable=False)

    # Human-readable reason set when extraction_status='rejected'.
    # Displayed on the dashboard so the user understands why the document
    # was not accepted. Null for all non-rejected documents.
    rejection_reason = Column(String(200), nullable=True)

    # Date when the medical event (vaccination, test, etc.) occurred.
    # Extracted from document content by GPT. Distinct from created_at (upload date).
    # May be null if extraction failed or document has no clear event date.
    event_date = Column(Date, nullable=True)

    # WhatsApp message ID (wamid) that triggered this document upload.
    # Used for document-level deduplication — prevents phantom uploads
    # when Meta retries webhooks after server restarts or timeouts.
    # Unique constraint ensures one Document per WhatsApp message.
    source_wamid = Column(String(200), nullable=True, unique=True, index=True)

    # Storage backend holding the file for this document.
    # 'gcp'      — stored in GCP Cloud Storage (primary, preferred)
    # 'supabase' — stored in Supabase private bucket (fallback or pre-migration)
    # The sync job migrates 'supabase' rows to GCP over time.
    storage_backend = Column(String(20), nullable=False, server_default="supabase")

    # Timestamp when the document was uploaded.
    # Indexed for daily upload limit check queries.
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

    # Number of automatic replay attempts made after extraction failure.
    # Capped at EXTRACTION_MAX_AUTO_RETRIES (3) by the replay cron.
    retry_count = Column(Integer, nullable=False, server_default="0")

    # SHA-256 hex digest of the raw file bytes.
    # Used to detect duplicate uploads and skip re-extraction when the
    # same file is uploaded again for the same pet.
    content_hash = Column(String(64), nullable=True)

    # Model-rated confidence for the extraction result (0.0–1.0).
    # Values below EXTRACTION_LOW_CONFIDENCE_THRESHOLD trigger a second-pass retry.
    extraction_confidence = Column(Float, nullable=True)

    # 1–2 sentence plain-language summary of key findings, populated by GPT
    # for Diagnostic documents (blood panels, imaging, etc.). Null for all
    # other document categories.
    diagnostic_summary = Column(Text, nullable=True)

    # Vet recommendations that are NOT diet instructions (type: activity, rest,
    # follow_up, other). Stored as a JSONB array so they can be surfaced on
    # the dashboard without a separate table. Each entry mirrors the GPT schema:
    # {type, description, linked_condition, duration, notes}.
    # Null when no non-diet recommendations were extracted.
    non_diet_recommendations = Column(JSONB, nullable=True)

    # --- Relationships ---

    # Back-reference to the pet this document belongs to.
    pet = relationship("Pet", back_populates="documents")
