"""
PetCircle Phase 1 — Nudge Model

Stores actionable health nudges generated by the nudge engine.
Each nudge represents a recommended action for the pet parent,
prioritized by urgency and categorized by health domain.

Constraints:
    - pet_id: FK to pets(id), ON DELETE CASCADE
    - priority: one of 'urgent', 'high', 'medium'
    - category: one of 'vaccine', 'deworming', 'flea', 'condition', 'nutrition', 'grooming', 'checkup'
    - source: 'record' (data-driven) or 'ai' (GPT-generated)
    - trigger_type: 'cron', 'upload', or 'inactivity'
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, Column, Date, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database import Base


class Nudge(Base):
    """
    A health action nudge for a pet.

    Nudges are generated by analyzing the pet's preventive records,
    conditions, nutrition gaps, and grooming status. They appear in
    the Action Plan screen and drive cart pre-population.

    mandatory nudges cannot be dismissed.
    orderable nudges have associated cart items.
    """

    __tablename__ = "nudges"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    pet_id = Column(UUID(as_uuid=True), ForeignKey("pets.id", ondelete="CASCADE"), index=True, nullable=False)
    category = Column(String(30), nullable=False)   # vaccine, deworming, flea, condition, nutrition, grooming, checkup
    priority = Column(String(10), nullable=False)    # urgent, high, medium
    icon = Column(String(10), nullable=True)
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    mandatory = Column(Boolean, nullable=False, default=False)
    orderable = Column(Boolean, nullable=False, default=False)
    price = Column(String(20), nullable=True)
    order_type = Column(String(30), nullable=True)   # medicine, homeVet, supplement, grooming
    cart_item_id = Column(String(10), nullable=True)
    dismissed = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Phase 7 — Nudge engine columns
    source = Column(String(20), default="record")       # 'record' or 'ai'
    wa_status = Column(String(20), nullable=True)        # NULL / pending / sent / failed / skipped
    wa_sent_at = Column(DateTime, nullable=True)
    wa_message_id = Column(String(100), nullable=True)
    trigger_type = Column(String(20), default="cron")    # cron / upload / inactivity
    expires_at = Column(Date, nullable=True)
    acted_on = Column(Boolean, default=False)

    # Relationships
    pet = relationship("Pet")
