"""
PetCircle Phase 1 — User Model

Mirrors the 'users' table with PII field-level encryption.
Mobile number serves as the unique identifier for WhatsApp-based authentication.

PII protection:
    - mobile_number: Fernet-encrypted, non-deterministic
    - mobile_hash: SHA-256 hash for indexed lookups (unique)
    - pincode, email: Fernet-encrypted

Constraints:
    - mobile_hash: UNIQUE, NOT NULL — one account per WhatsApp number
    - is_deleted: soft delete flag — physical deletes are never performed
    - Cascade: deleting a user cascades to pets (defined on pets FK side)
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.database import Base


class User(Base):
    """
    Represents a pet parent registered via WhatsApp.

    Mobile number is the unique identifier — no email or password auth in Phase 1.
    Soft delete via is_deleted flag; physical delete is never used.
    """

    __tablename__ = "users"

    # Primary key — UUID generated by PostgreSQL (gen_random_uuid)
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # WhatsApp mobile number — encrypted with Fernet for PII protection.
    # Stored as ciphertext; decrypt with app.core.encryption.decrypt_field.
    mobile_number = Column(String(500), unique=False, nullable=False)

    # Deterministic SHA-256 hash of the mobile number for indexed lookups.
    # Allows finding users by phone without decrypting all rows.
    mobile_hash = Column(String(64), unique=True, nullable=False, index=True)

    # Full phone number for display in Supabase table UI and admin dashboard.
    # Stored in plaintext — not a security field, used for quick identification.
    mobile_display = Column(String(20), nullable=True)

    # Full name collected during onboarding.
    full_name = Column(String(120), nullable=False)

    # Indian pincode — encrypted with Fernet for PII protection.
    pincode = Column(String(500), nullable=True)

    # Email address — encrypted with Fernet for PII protection.
    email = Column(String(500), nullable=True)

    # Consent flag — True once user has accepted terms.
    # Timestamp of consent is the created_at when consent_given=True.
    consent_given = Column(Boolean, default=False)

    # Onboarding state — tracks multi-step WhatsApp conversation.
    # States: awaiting_consent, awaiting_name, awaiting_pincode,
    #         awaiting_pet_name, awaiting_pet_photo, awaiting_species,
    #         awaiting_species_confirm, awaiting_breed_confirm,
    #         awaiting_breed,
    #         awaiting_gender, awaiting_dob, awaiting_weight,
    #         awaiting_neutered, awaiting_documents, complete
    onboarding_state = Column(String(30), default="awaiting_consent")

    # Deadline for the post-onboarding document upload window.
    # Set when entering awaiting_documents state, cleared on exit.
    # Nullable — only populated during the upload window.
    doc_upload_deadline = Column(DateTime(timezone=True), nullable=True)

    # Flag set when _finalize_onboarding() fires while document extractions are
    # still in-flight (extraction_status='pending'). When True, the dashboard
    # link is held back from the finalization message and instead appended to
    # the deferred care-plan message once all docs finish processing.
    dashboard_link_pending = Column(Boolean, default=False, nullable=False)

    # Timestamp when the user completed onboarding (state reached 'complete').
    # Used by nudge_scheduler as O (Onboarding Day) to compute O+N nudge slots.
    # Nullable — None until onboarding finishes.
    onboarding_completed_at = Column(DateTime(timezone=True), nullable=True)

    # Reminder ID stored while user is in awaiting_reschedule_date state.
    # When user taps "Schedule For ()" on a reminder, message_router stores
    # the reminder ID here and waits for the user to reply with a date.
    # SET NULL automatically if the reminder is deleted.
    active_reminder_id = Column(
        UUID(as_uuid=True),
        ForeignKey("reminders.id", ondelete="SET NULL", use_alter=True),
        nullable=True,
    )

    # Transient onboarding metadata (JSONB).
    # Stores step-local state that doesn't deserve its own column:
    #   food_type, breed_age_attempts, preventive_attempts, needs_species, etc.
    # Cleared to None when onboarding completes.
    onboarding_data = Column(JSONB, nullable=True)

    # Soft delete flag — when True, user is treated as deleted.
    # No physical delete is ever performed; this preserves audit trail.
    is_deleted = Column(Boolean, default=False)

    # Timestamps managed by PostgreSQL DEFAULT NOW().
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # --- Checkout Preferences ---
    # Last-used delivery address (free text). Saved automatically after every
    # successful order so the next checkout can prefill the address field.
    delivery_address = Column(Text, nullable=True)

    # Last payment method used: 'cod' | 'upi' | 'card'.
    # Pre-selects the correct radio button on the next checkout.
    payment_method_pref = Column(String(10), nullable=True)

    # Fernet-encrypted UPI VPA (e.g. name@okicici), fetched from Razorpay API
    # after a successful UPI payment. Passed as prefill.vpa on the next UPI order.
    saved_upi_id = Column(String(500), nullable=True)

    # --- Order Flow State ---
    # Tracks the current step in the WhatsApp order conversation.
    # States: awaiting_order_category, awaiting_pet_reco,
    #         awaiting_reco_sel, awaiting_order_items,
    #         awaiting_order_pet, awaiting_order_confirm
    # Nullable — None when user is not in an order flow.
    order_state = Column(String(30), nullable=True)

    # --- Agentic Edit Flow State ---
    # Set to "agentic_edit" when user is in an AI-driven profile edit conversation.
    # Cleared to None when the edit session completes or is cancelled.
    edit_state = Column(String(30), nullable=True)

    # Transient session data for the agentic edit flow.
    # Structure: {"messages": [...], "selected_pet_id": "<uuid>|null"}
    # Cleared on session completion.
    edit_data = Column(JSONB, nullable=True)

    # Reference to the draft order being built during the order flow.
    # SET NULL on delete so user record isn't affected if order is cleaned up.
    # use_alter=True avoids circular FK dependency during table creation.
    active_order_id = Column(
        UUID(as_uuid=True),
        ForeignKey("orders.id", ondelete="SET NULL", use_alter=True),
        nullable=True,
    )

    # Relationship to pets — one user can have up to MAX_PETS_PER_USER pets.
    # Cascade defined on the Pet model's foreign key side.
    pets = relationship("Pet", back_populates="user")

    # Relationship to orders — one user can have many orders.
    # foreign_keys specified to avoid ambiguity with active_order_id FK.
    orders = relationship("Order", back_populates="user", foreign_keys="Order.user_id")

    # Custom preventive items added by this user (supplements, vaccines, etc.).
    custom_preventive_items = relationship("CustomPreventiveItem", back_populates="user")
