"""
test_dashboard_endpoints.py â€” API-level tests for all dashboard endpoints.

Uses the FULL_TOKEN generated by scripts/run_onboarding.py (stored in
frontend/tests/.tokens). Tests hit the real database (dev Supabase).

Run after starting the backend:
    cd backend && uvicorn app.main:app --reload --port 8000

Then:
    cd backend && python -m pytest tests/test_dashboard_endpoints.py -v
"""

import os

import httpx
import pytest

# â”€â”€â”€ Read token from .tokens file â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
TOKENS_FILE = os.path.join(
    os.path.dirname(__file__), "..", "frontend", "tests", ".tokens"
)

FULL_TOKEN = None
EMPTY_TOKEN = None

if os.path.exists(TOKENS_FILE):
    for line in open(TOKENS_FILE).read().strip().splitlines():
        if line.startswith("FULL_TOKEN="):
            FULL_TOKEN = line.split("=", 1)[1]
        elif line.startswith("EMPTY_TOKEN="):
            EMPTY_TOKEN = line.split("=", 1)[1]

BASE_URL = "http://localhost:8000"

PASS = 0
FAIL = 0


def check(name: str, condition: bool, detail: str = ""):
    global PASS, FAIL
    if condition:
        PASS += 1
        print(f"  [PASS] {name}")
    else:
        FAIL += 1
        print(f"  [FAIL] {name} -- {detail}")


# â”€â”€â”€ Pytest skip if no token â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
@pytest.fixture(scope="module")
def full_token():
    if not FULL_TOKEN:
        pytest.skip("No FULL_TOKEN found. Run `python scripts/run_onboarding.py` first.")
    return FULL_TOKEN


@pytest.fixture(scope="module")
def empty_token():
    if not EMPTY_TOKEN:
        pytest.skip("No EMPTY_TOKEN found.")
    return EMPTY_TOKEN


@pytest.fixture(scope="module")
def client():
    return httpx.Client(base_url=BASE_URL, timeout=30.0)


# â”€â”€â”€ Dashboard Data â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestDashboardData:
    def test_get_dashboard_full(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}")
        assert r.status_code == 200, f"Expected 200, got {r.status_code}: {r.text[:200]}"
        data = r.json()
        assert "pet" in data
        assert data["pet"]["name"] == "Zayn"
        assert data["pet"]["species"] == "dog"
        assert data["pet"]["breed"] == "Labrador Retriever"
        assert "preventive_records" in data
        assert len(data["preventive_records"]) > 0

    def test_get_dashboard_empty(self, client, empty_token):
        r = client.get(f"/dashboard/{empty_token}")
        assert r.status_code == 200
        data = r.json()
        assert "pet" in data
        assert data["pet"]["name"] == "Skippy"

    def test_invalid_token_returns_error(self, client):
        r = client.get("/dashboard/invalid-token-abc000")
        assert r.status_code in (404, 403, 401), f"Got {r.status_code}"


# â”€â”€â”€ Weight â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestWeight:
    def test_update_weight(self, client, full_token):
        r = client.patch(f"/dashboard/{full_token}/weight", json={"weight": 29.5})
        assert r.status_code == 200
        data = r.json()
        assert "new_weight" in data or "status" in data

    def test_get_weight_history(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/weight-history")
        assert r.status_code == 200
        data = r.json()
        assert "entries" in data or isinstance(data, list)

    def test_add_weight_entry(self, client, full_token):
        r = client.post(f"/dashboard/{full_token}/weight-history", json={
            "weight": 28.0,
            "recorded_at": "2025-01-15",
            "note": "After morning walk"
        })
        assert r.status_code in (200, 201)


# â”€â”€â”€ Preventive Records â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestPreventiveRecords:
    def test_update_preventive_date(self, client, full_token):
        r = client.patch(f"/dashboard/{full_token}/preventive", json={
            "item_name": "Deworming",
            "last_done_date": "2025-02-01"
        })
        assert r.status_code in (200, 404), f"Got {r.status_code}: {r.text[:200]}"

    def test_update_preventive_frequency(self, client, full_token):
        r = client.patch(f"/dashboard/{full_token}/preventive-frequency", json={
            "item_name": "Deworming",
            "recurrence_days": 90
        })
        assert r.status_code in (200, 404)


# â”€â”€â”€ Diet Items â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestDietItems:
    added_id: str = None

    def test_get_diet_items(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/diet-items")
        assert r.status_code == 200
        data = r.json()
        assert isinstance(data, list)

    def test_add_diet_item(self, client, full_token):
        r = client.post(f"/dashboard/{full_token}/diet-items", json={
            "name": "Test Food API",
            "type": "packaged",
            "quantity": "1 cup",
            "frequency": "daily"
        })
        assert r.status_code in (200, 201)
        data = r.json()
        assert "id" in data
        TestDietItems.added_id = data["id"]

    def test_update_diet_item(self, client, full_token):
        if not TestDietItems.added_id:
            pytest.skip("No diet item was added")
        r = client.put(f"/dashboard/{full_token}/diet-items/{TestDietItems.added_id}", json={
            "name": "Test Food API Updated",
            "quantity": "2 cups"
        })
        assert r.status_code in (200, 204)

    def test_delete_diet_item(self, client, full_token):
        if not TestDietItems.added_id:
            pytest.skip("No diet item was added")
        r = client.delete(f"/dashboard/{full_token}/diet-items/{TestDietItems.added_id}")
        assert r.status_code in (200, 204)


# â”€â”€â”€ Hygiene Preferences â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestHygienePreferences:
    pref_id: str = None

    def test_get_hygiene_preferences(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/hygiene-preferences")
        assert r.status_code == 200
        data = r.json()
        assert isinstance(data, list)
        if len(data) > 0:
            TestHygienePreferences.pref_id = data[0]["id"]

    def test_update_hygiene_preference(self, client, full_token):
        if not TestHygienePreferences.pref_id:
            pytest.skip("No hygiene preference found")
        r = client.put(
            f"/dashboard/{full_token}/hygiene-preferences/{TestHygienePreferences.pref_id}",
            json={"reminder_enabled": True}
        )
        assert r.status_code in (200, 204)

    def test_update_hygiene_date(self, client, full_token):
        if not TestHygienePreferences.pref_id:
            pytest.skip("No hygiene preference found")
        r = client.patch(
            f"/dashboard/{full_token}/hygiene-preferences/{TestHygienePreferences.pref_id}/date",
            json={"last_done": "2025-03-10"}
        )
        assert r.status_code in (200, 204)


# â”€â”€â”€ Conditions â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestConditions:
    condition_id: str = None
    med_id: str = None
    mon_id: str = None

    def test_add_condition(self, client, full_token):
        r = client.post(f"/dashboard/{full_token}/conditions", json={
            "name": "API Test Condition",
            "notes": "Created by test_dashboard_endpoints.py"
        })
        assert r.status_code in (200, 201)
        data = r.json()
        assert "condition_id" in data
        TestConditions.condition_id = data["condition_id"]

    def test_add_medication_to_condition(self, client, full_token):
        if not TestConditions.condition_id:
            pytest.skip("No condition was added")
        r = client.post(
            f"/dashboard/{full_token}/conditions/{TestConditions.condition_id}/medications",
            json={
                "name": "TestMed 10mg",
                "dosage": "once daily",
                "notes": "Test"
            }
        )
        assert r.status_code in (200, 201)
        data = r.json()
        TestConditions.med_id = data.get("medication_id")

    def test_add_monitoring_to_condition(self, client, full_token):
        if not TestConditions.condition_id:
            pytest.skip("No condition was added")
        r = client.post(
            f"/dashboard/{full_token}/conditions/{TestConditions.condition_id}/monitoring",
            json={
                "name": "Blood Panel",
                "frequency_days": 90,
                "notes": "API test"
            }
        )
        assert r.status_code in (200, 201)
        data = r.json()
        TestConditions.mon_id = data.get("monitoring_id")

    def test_delete_medication(self, client, full_token):
        if not TestConditions.med_id:
            pytest.skip("No medication was added")
        r = client.delete(f"/dashboard/{full_token}/medications/{TestConditions.med_id}")
        assert r.status_code in (200, 204)

    def test_delete_monitoring(self, client, full_token):
        if not TestConditions.mon_id:
            pytest.skip("No monitoring was added")
        r = client.delete(f"/dashboard/{full_token}/monitoring/{TestConditions.mon_id}")
        assert r.status_code in (200, 204)

    def test_delete_condition(self, client, full_token):
        if not TestConditions.condition_id:
            pytest.skip("No condition was added")
        r = client.delete(f"/dashboard/{full_token}/conditions/{TestConditions.condition_id}")
        assert r.status_code in (200, 204)


# â”€â”€â”€ Contacts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestContacts:
    contact_id: str = None

    def test_add_contact(self, client, full_token):
        r = client.post(f"/dashboard/{full_token}/contacts", json={
            "type": "veterinarian",
            "name": "Dr. API Test",
            "phone": "9000000001",
            "clinic_name": "API Test Clinic"
        })
        assert r.status_code in (200, 201)
        data = r.json()
        TestContacts.contact_id = data.get("contact_id")

    def test_update_contact(self, client, full_token):
        if not TestContacts.contact_id:
            pytest.skip("No contact was added")
        r = client.put(f"/dashboard/{full_token}/contacts/{TestContacts.contact_id}", json={
            "name": "Dr. API Test Updated"
        })
        assert r.status_code in (200, 204)

    def test_delete_contact(self, client, full_token):
        if not TestContacts.contact_id:
            pytest.skip("No contact was added")
        r = client.delete(f"/dashboard/{full_token}/contacts/{TestContacts.contact_id}")
        assert r.status_code in (200, 204)


# â”€â”€â”€ Cart â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestCart:
    product_id: str = "test-product-001"

    def test_get_cart(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/cart")
        assert r.status_code == 200
        data = r.json()
        assert "items" in data

    def test_toggle_cart_item(self, client, full_token):
        # Toggle a recommendation item into the cart
        # First get recommendations to find a real product_id
        recs_r = client.get(f"/dashboard/{full_token}/cart/recommendations")
        assert recs_r.status_code == 200
        recs = recs_r.json()

        if not recs:
            pytest.skip("No recommendations available to toggle")

        product_id = recs[0].get("product_id")
        if not product_id:
            pytest.skip("Recommendation has no product_id")
        TestCart.product_id = product_id

        r = client.post(f"/dashboard/{full_token}/cart/toggle/{product_id}")
        assert r.status_code == 200

    def test_get_cart_recommendations(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/cart/recommendations")
        assert r.status_code == 200
        data = r.json()
        assert isinstance(data, list)

    def test_apply_invalid_coupon(self, client, full_token):
        r = client.post(f"/dashboard/{full_token}/cart/apply-coupon", json={
            "code": "INVALIDCOUPON123"
        })
        # Either 400 or 200 with valid=False
        assert r.status_code in (200, 400)
        if r.status_code == 200:
            data = r.json()
            assert data.get("valid") == False

    def test_place_cod_order(self, client, full_token):
        # Add item to cart first
        recs_r = client.get(f"/dashboard/{full_token}/cart/recommendations")
        if recs_r.status_code == 200 and recs_r.json():
            rec = recs_r.json()[0]
            product_id = rec.get("product_id", "test-prod")
            # Add to cart
            client.post(f"/dashboard/{full_token}/cart/toggle/{product_id}")

        r = client.post(f"/dashboard/{full_token}/place-order", json={
            "payment_method": "cod",
            "address": {
                "name": "API Test User",
                "line": "123 Test Street, Mumbai 400001",
                "tag": "Home"
            }
        })
        assert r.status_code in (200, 201, 422), f"Got {r.status_code}: {r.text[:300]}"
        if r.status_code in (200, 201):
            data = r.json()
            assert "order_id" in data


# â”€â”€â”€ Nudges â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestNudges:
    nudge_id: str = None

    def test_get_nudges(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/nudges")
        assert r.status_code == 200
        data = r.json()
        assert isinstance(data, list)
        if len(data) > 0:
            TestNudges.nudge_id = data[0].get("id")

    def test_dismiss_nudge(self, client, full_token):
        if not TestNudges.nudge_id:
            pytest.skip("No nudge to dismiss")
        r = client.patch(f"/dashboard/{full_token}/nudges/{TestNudges.nudge_id}/dismiss")
        assert r.status_code in (200, 204)


# â”€â”€â”€ AI Endpoints â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestAIEndpoints:
    def test_get_health_summary(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/health-summary", timeout=60.0)
        assert r.status_code == 200
        data = r.json()
        assert "summary" in data
        assert len(data["summary"]) > 10

    def test_get_nutrition_analysis(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/nutrition-analysis", timeout=60.0)
        assert r.status_code in (200, 404)  # 404 if no diet items

    def test_get_condition_recommendations(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/condition-recommendations", timeout=60.0)
        assert r.status_code == 200
        data = r.json()
        assert "recommendations" in data

    def test_get_vet_questions(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/vet-questions", timeout=60.0)
        assert r.status_code == 200
        data = r.json()
        assert isinstance(data, list)

    def test_get_condition_timeline(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/condition-timeline")
        assert r.status_code == 200
        data = r.json()
        assert "events" in data

    def test_get_last_vet_visit(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/last-vet-visit")
        assert r.status_code == 200

    def test_get_health_trends(self, client, full_token):
        r = client.get(f"/dashboard/{full_token}/trends")
        assert r.status_code == 200


# â”€â”€â”€ Document Upload â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestDocumentUpload:
    def test_upload_pdf_document(self, client, full_token):
        """Upload a real PDF from pet condition docs."""
        import os
        docs_dir = os.path.join(
            os.path.dirname(__file__), "..", "..", "..",
            "pet condition docs"
        )
        pdf_path = os.path.join(docs_dir, "CBC_12_02_25.pdf")
        if not os.path.exists(pdf_path):
            pytest.skip(f"Test PDF not found: {pdf_path}")

        with open(pdf_path, "rb") as f:
            r = client.post(
                f"/dashboard/{full_token}/upload-document",
                files={"file": ("CBC_12_02_25.pdf", f, "application/pdf")}
            )
        assert r.status_code in (200, 201), f"Got {r.status_code}: {r.text[:300]}"
        data = r.json()
        assert "document_id" in data or "id" in data

    def test_invalid_token_upload_rejected(self, client):
        """Upload to invalid token should be rejected."""
        import io
        fake_pdf = io.BytesIO(b"%PDF-1.4 fake")
        r = client.post(
            "/dashboard/invalid-token-abc/upload-document",
            files={"file": ("test.pdf", fake_pdf, "application/pdf")}
        )
        assert r.status_code in (403, 404, 401)


# â”€â”€â”€ Empty Token Tests â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

class TestEmptyDashboard:
    def test_empty_dashboard_loads(self, client, empty_token):
        r = client.get(f"/dashboard/{empty_token}")
        assert r.status_code == 200
        data = r.json()
        assert data["pet"]["name"] == "Skippy"

    def test_empty_diet_items(self, client, empty_token):
        r = client.get(f"/dashboard/{empty_token}/diet-items")
        assert r.status_code == 200
        # Empty dashboard should return empty or very small list
        data = r.json()
        assert isinstance(data, list)

    def test_empty_conditions_list(self, client, empty_token):
        r = client.get(f"/dashboard/{empty_token}")
        assert r.status_code == 200
        data = r.json()
        conditions = data.get("conditions", [])
        assert isinstance(conditions, list)


# â”€â”€â”€ Standalone runner â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def main():
    """Run a quick sanity check without pytest."""
    global PASS, FAIL

    if not FULL_TOKEN:
        print("âŒ No FULL_TOKEN â€” run scripts/run_onboarding.py first")
        return

    c = httpx.Client(base_url=BASE_URL, timeout=30.0)
    print(f"\n{'='*60}")
    print("DASHBOARD ENDPOINT SANITY CHECK")
    print(f"{'='*60}")

    r = c.get(f"/dashboard/{FULL_TOKEN}")
    check("GET /dashboard/{token}", r.status_code == 200, f"status={r.status_code}")
    if r.status_code == 200:
        data = r.json()
        check("Pet name = Zayn", data["pet"]["name"] == "Zayn")
        check("Has preventive records", len(data.get("preventive_records", [])) > 0)

    r = c.get(f"/dashboard/{FULL_TOKEN}/nudges")
    check("GET /nudges", r.status_code == 200)

    r = c.get(f"/dashboard/{FULL_TOKEN}/cart")
    check("GET /cart", r.status_code == 200)

    r = c.get(f"/dashboard/{FULL_TOKEN}/cart/recommendations")
    check("GET /cart/recommendations", r.status_code == 200)

    r = c.get(f"/dashboard/{FULL_TOKEN}/diet-items")
    check("GET /diet-items", r.status_code == 200)

    r = c.get(f"/dashboard/{FULL_TOKEN}/hygiene-preferences")
    check("GET /hygiene-preferences", r.status_code == 200)

    r = c.get("/dashboard/invalid-token-xyz/nudges")
    check("Invalid token returns 4xx", r.status_code in (400, 403, 404))

    print(f"\n{'='*60}")
    print(f"RESULTS: {PASS} PASS, {FAIL} FAIL")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()

